server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barcodehub?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # Pode ser "create", "update", "validate" ou "none"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect